### ISSUE TITLE
erreur au lancement 

### ISSUE THREAD

**Issue by bend94** [mathman/tydom#6]
Bonjour

J'ai installé ton appli sur mon raspberry pi 
j'ai setuper les variables 

const port = '333';
const host = '192.168.1.31';
const username = '001A2505E9E7';
const password = 'xxxxx';
const isremote = 0;

J'ai lancé l'application et j'ai cette erreur

root@DomoticzPi:/home/pi/tydom/tydom# node  app.js
Connecting to "192.168.1.31"...
(node:4254) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)

/home/pi/tydom/tydom/node_modules/got/dist/source/core/index.js:962
            error = error instanceof timed_out_1.TimeoutError ? new TimeoutError(error, this.timings, this) : new RequestError(error.message, error, this);
                                                                                                              ^
RequestError: write EPROTO 006AFEB6:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:../deps/openssl/openssl/ssl/statem/extensions.c:908:

    at ClientRequest.<anonymous> (/home/pi/tydom/tydom/node_modules/got/dist/source/core/index.js:962:111)
    at Object.onceWrapper (node:events:642:26)
    at ClientRequest.emit (node:events:539:35)
    at ClientRequest.origin.emit (/home/pi/tydom/tydom/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)

Merci de ton aide

**Comment by bend94** [comment]
J'ai modifié const isremote = 0; ==> const isremote = 1;

ce coup ci ca se lance mais en http://@ip:333 rien n'apparait 
et en netstat -an |grep 333 aucun port est ouvert
